### ISSUE TITLE
Social Buttons are unlinked to Website

### ISSUE THREAD

**Issue by T-Wall** [mithraiclabs/psyoptions-frontend#760]
A user noticed when scrolling to the bottom of the landing page, none of the social links are clickable, thus not taking them to the required site. ie When clicking on twitter it does nothing.

![](https://cdn.discordapp.com/attachments/821594418321686548/917542881399566336/Capture_decran_2021-12-06_a_23.26.54.png)

**Comment by haroonpsyoptions** [comment]
@Taylor123 Can you please provide me a links to add here.

**Comment by haroonpsyoptions** [comment]
@Taylor123 and @T-Wall I just tested it and found that this issue is already resolved.

**Comment by T-Wall** [comment]
Twitter:  https://twitter.com/PsyOptions
Github: https://github.com/mithraiclabs
Telegram: https://t.me/psyoptions
Discord: https://discord.com/invite/MgDdJKgZJc
Medium: https://medium.com/psyoptions

**Comment by T-Wall** [comment]
@haroonpsyoptions I am looking at it now and it is not fixed on this website https://trade.psyoptions.io/#/

**Comment by haroonpsyoptions** [comment]
@T-Wall Yes apology I haven't tested it on landing page but the other page where it was working. Issue is still there for landing page only.
